# Generated by Django 3.2.14 on 2022-07-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='accounts.useraccount', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='accounts.useraccount', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
